spring:
  application:
     name: game-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: simplecasino-game-service

server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: false
  client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000